version: '3'

# Services and their settings we are going to use
# Restart if there is a problem unless stopped i guess?
services:
    nginx:
        container_name: nginx
        env_file:
            - .env
        build:
            context: ./
            dockerfile: requirements/nginx/Dockerfile
        ports:
            - 443:443
        volumes:
            - wordpress_data:/var/www/html
        restart: unless-stopped
        networks:
            - inception
        depends_on:
            - wordpress

    mariadb:
        container_name: mariadb
        env_file:
            - .env
        build:
            context: ./
            dockerfile: requirements/mariadb/Dockerfile
        args:
            DB_NAME: ${DATABASE_NAME}
            DB_USER: ${DATABASE_USER}
            DB_PASS: ${DATABASE_USER_PASS}
            DB_ROOT: ${DATABASE_ROOT}
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - inception
        restart: unless-stopped

    # Has a dependency of database obviously
    wordpress:
        container_name: wordpress
        env_file:
            - .env
        depends_on:
            - mariadb
        build:
            context: ./
            dockerfile: requirements/wordpress/Dockerfile
        args:
            WP_ADMIN_NAME: ${WP_ADMIN} # build time arguments are making dockerfiles
            WP_ADMIN_PW: ${WP_ADMIN_PW} # more dunamic and flexible
            WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        volumes:
            - wordpress_data:/var/www/html
        restart: unless-stopped
        networks:
            - inception

# Volume locations and settings
volumes:
    mariadb_data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: /home/zstenger/data/mariadb
    wordpress_data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: /home/zstenger/data/mariadb

networks:
    inception:
        driver: bridge
