version: '3'

# Services and their settings we are going to use here
# Alaways restart if there is a problem
services:
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build:
      context: ./
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env

# Has a dependency of database
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME} # build time arguments are making dockerfiles
        DB_USER: ${DB_USER} # more dunamic and flexible
        DB_PASS: ${DB_PASS}
    restart: always
    env_file:
      - .env
    networks:
      - network

# Volume locations and settings
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  network:
    driver: bridge
