version: "3"

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file: .env
    ports:
      - '443:443'
    volumes:
      - problem-files:/var/www/html
    networks:
      - ok
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    networks:
      - ok
    volumes:
      - problem-db:/var/www/html
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - problem-files:/var/www/html
    networks:
      - ok
    restart: always

networks:
  ok:
    driver: bridge

volumes:
  problem-files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/zstenger/problem_files"
      # device: ${INCEPTION_PATH}/problem_files

  problem-db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/zstenger/problem_db"
      # device: ${INCEPTION_PATH}/problem_db
